# Generated by Django 5.1.6 on 2025-02-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdfs/'),
        ),
    ]
