# Generated by Django 5.1.6 on 2025-02-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_alter_contact_image_alter_contact_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/pdfs/'),
        ),
    ]
